
server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?serverTimezone=GMT%2B8
    username: root
    password: 1222



mybatis:
  mapper-locations: classpath:/com/example/demo/dao/*.xml
  # 这样就可以在mapperXML中用简单的Account代替冗长的cn.kgc.entities.Account
  type-aliases-package: com.example.demo.pojo
